export const SLIDES = [
  {
    id: "root",
    tag: "the climb",
    eyebrow: "Root · why we're here",
    fragment: `How computers and data work — a climb from switches to AI.`,
    sub: `Why bother? You can't judge what today's AI can and can't do without it — and every rung is built on the one below.`,
    anchor: `The opening frame and the motivation for the whole lecture: you cannot fairly judge modern AI's powers and limits without a working grasp of how computers compute and how data is used. Offer three interchangeable lenses on the same field — (1) information becomes real by climbing layers, electricity at the bottom, meaning at the top; (2) computing is transforming representations of information under constraints of resources; (3) a climb from physical switches up to AI, each rung built on the one below and usable without understanding the bottom. Stay at this framing altitude: name the journey, do not descend into any single rung yet.`,
  },
  {
    id: "switches",
    tag: "switches",
    eyebrow: "The machine · bits",
    fragment: `It's all switches.`,
    sub: `On or off, 1 or 0 — every number, letter, text and image is huge piles of on/off, dressed up by a convention for reading them.`,
    anchor: `Billions of transistors acting as extremely fast switches with no moving parts. Two agreed states are enough to encode any number, letter, image or sound, because bits compose. The point to seat firmly, because the whole deck leans on it later: there is no picture or song inside the machine — only bit patterns plus a convention for reading them. Meaning is not in the bits; it is in the agreement about how to read them. This is the first instance of "the map is not the territory" (named at recurring) and the seed of every representation move later — bits, then points-in-space, then learned features. Stay classical; no quantum-computing detours. Differentiate from the next rung: this slide is about representation (world → bits under a convention), not about what the CPU does to those bits.`,
    },
    {
    id: "steps",
    tag: "tiny steps",
    eyebrow: "The machine · the CPU",
    fragment: `The CPU only does tiny dumb steps — insanely fast.`,
    sub: `Move, copy, add, compare — billions a second. Computation is symbols pushed by mechanical rules. No cleverness in any step; all of it is in the stacking.`,
    anchor: `A processor executes only trivial operations: arithmetic, comparison, moving data, jumping to another instruction. Nothing it does is individually clever; apparent intelligence is composition at scale. It is deterministic — same inputs, same steps, same result, every time. Stress the "no magic, mechanical, blindingly fast" nature. This rung introduces the deck's core deflationary move — intelligence is composition of dumb parts, not a special ingredient — which the AI section will both honour and complicate: the same "just composition" logic that demystifies the CPU will, at enough scale, produce behaviour nobody explicitly built (the map emerging from the composition faster than anyone authored it). Do not raise that tension here; just make the composition claim cleanly, because it is the claim the top of the deck will lean on and qualify. Differentiate from the algorithm rung later: this slide is about the CPU's dumb-but-fast vocabulary and determinism, NOT about clever recipes or how cost scales.`
    },
    {
    id: "os",
    tag: "the OS",
    eyebrow: "The machine · the referee",
    fragment: `One machine, shared among many.`,
    sub: `The operating system rations processor and memory so fast that your dozens of programs all feel like they run at once — most of the time.`,
    anchor: `The operating system is the shared referee: it hands out the processor, memory and files among many programs, switching between them thousands of times a second so tasks appear simultaneous even on a few cores. It also isolates them — each program gets its own patch of memory and can't trample another's — so one crash doesn't take down the machine. This is a first taste of a managed illusion built on limited resources: a theme that returns as the memory tradeoff, and structurally again when one frozen model is shared across countless uses (trainonce). Note the "most times": under heavy load the illusion cracks and things stutter — illusions built on rationed resources have a breaking point. Keep it concrete; no scheduling algorithms or kernel internals.`,
  },
  {
    id: "memory",
    tag: "memory",
    eyebrow: "The machine · memory",
    fragment: `Fetching is the slow part, not thinking.`,
    sub: `Fast memory is tiny and near; big memory is far and slow. Speed is mostly keeping data close — the first hard tradeoff.`,
    anchor: `Memory is a hierarchy from small-fast (on-chip caches) to large-slow (disk, network). Moving data to the processor usually costs far more than the computation itself. This is why caching, locality and "don't redo work" dominate performance, and why feeding data to GPUs matters as much as their arithmetic — a direct set-up for the scale rung, where the AI boom turns out to be a data-movement-and-arithmetic boom. Make this the deck's first explicit, physical tradeoff (small-fast vs large-slow), the concrete anchor for the abstract "everything is a tradeoff" named at recurring: here you can point at it. Keep concrete; this is about the cost of moving data, not about algorithms.`,
  },
  {
    id: "code",
    tag: "code",
    eyebrow: "Instructing · language",
    fragment: `Code is machine steps written in words.`,
    sub: `A translation chain: human-readable language ground down, layer by layer, into the tiny operations the CPU actually runs. Exactly, every time.`,
    anchor: `Programming languages let humans write instructions in something close to words; a translator (compiler or interpreter) grinds that down, layer by layer, into the CPU's tiny operations. Higher-level languages are more expressive and forgiving but further from the metal; lower-level ones give more control and more pain — a tradeoff (expressiveness vs control) that rhymes with every other tradeoff in the deck. The key point, and the one the AI section will overturn: this translation is EXACT and inspectable. The machine only ever runs tiny steps; code is a human-shaped surface over them, mechanically and faithfully translated — a compiler is correct, or it is a bug. Nothing new happens in the machine. Hold this "exact translation between layers" idea deliberately, because probably is precisely the rung where that guarantee is traded away for reach. Keep concrete; no syntax detours. Differentiate from the algorithm rung: this is about translation (words → steps), not about the cleverness or cost of the recipe.`,
  },
  {
    id: "algorithms",
    tag: "algorithms",
    eyebrow: "Instructing · efficiency",
    fragment: `An algorithm is a recipe — and how it scales is what matters.`,
    sub: `Same result, wildly different cost. Don't redo work, measure before optimizing, and beware the metric you chase.`,
    anchor: `An algorithm is a precise recipe: a finite list of steps that solves a problem. Many recipes give the same answer at wildly different cost; what matters is how cost GROWS as the input grows, because that decides what is feasible at all — scaling is the star here, and it returns transformed at the scale rung, where growth stops being a cost to fear and becomes the engine that produces new abilities. Fold in the performance wisdom grouped here: don't redo work (cache and reuse), measure before optimizing (intuition about the slow part is usually wrong), and beware that any metric becomes gamed once it is the target (Goodhart — a concrete instance of "the map is not the territory," and a live risk again when we grade learned models on proxies). Differentiate from the CPU rung: there the steps were dumb; here the cleverness lives in their order, and scaling is the star.`,
  },
  {
    id: "stacks",
    tag: "abstraction",
    eyebrow: "Assembling · interfaces",
    fragment: `Hard tasks are simpler tasks, sealed behind interfaces.`,
    sub: `Decompose the problem; hide each piece behind a clean "what" that conceals its messy "how". Name things, combine them — that's most of building.`,
    anchor: `The master move for complexity: decompose a hard task into simpler tasks, and wrap each behind an interface — a contract that promises WHAT a part does while concealing HOW it does it. Layers stack this way (hardware, OS, languages, libraries, apps), each trusting the one below. Naming and composition — name a capability, combine named capabilities — is very nearly all of building. You can change the how freely as long as the what holds. This is the constructive, load-bearing form of the deck's composition theme (steps introduced it as dumb parts; here composition becomes the deliberate discipline that builds everything) — and it sets up the sharpest contrast with AI: these interfaces promise their "what" exactly, whereas a learned layer only promises it probably. Differentiate from the next rung: this is the principle (decompose + interface = what/how); the next is the lived reality (you glue borrowed parts, and interfaces leak).`,
  },
  {
    id: "gluing",
    tag: "leaks",
    eyebrow: "Assembling · leaks",
    fragment: `You glue other people's parts — and every abstraction leaks.`,
    sub: `You rarely own the whole stack or build from scratch. The hidden complexity is deferred, not gone — and one day it pokes through.`,
    anchor: `The practical reality of building: almost nothing is written from scratch; you assemble existing blocks and trust the machinery behind each interface to behave. But abstractions leak — hidden complexity is deferred, not deleted. The day a borrowed library fails weirdly, a query is mysteriously slow, or an assumption you didn't know you had made breaks, the sealed "how" pokes through and forces you to look inside something you didn't write. Hence the craftsman's rule, which recurring will name as the first recurring idea: use the top, but understand one layer below. This matters more, not less, as we climb into AI — a probabilistic layer is the leakiest abstraction of all, and "understand one layer below" becomes the verifying step probably insists on keeping. Differentiate from the previous rung: that was about hiding complexity; this is about assembling borrowed parts and the leaks that follow.`,
  },
  {
    id: "defensive",
    tag: "defense",
    eyebrow: "Assembling · robustness",
    fragment: `Assume the outside will betray you.`,
    sub: `Networks drop, code drifts, truths diverge, inputs lie, split work collides, load surges — build to stay standing anyway.`,
    anchor: `Reliable systems are built defensively and flexibly, because in the real world things fail and change constantly: the network will fail, code and data will drift, multiple sources of truth will diverge, outside input cannot be trusted, splitting work across machines breeds race conditions, and rising load (scale) strains every resource. Good engineering expects all of this and keeps standing — validate inputs, tolerate failure, don't assume one true copy, guard shared work. Note that this defensive stance is the disposition the whole back half of the deck will demand of AI too: drift reappears literally when learned patterns go stale, "inputs lie" reappears as untrusted data becoming the program, and "expect to be wrong and stay standing" is exactly the posture calibrated uncertainty and the verifying step formalize. Keep it concrete and avoid security jargon. This is the "build for a hostile, changing world" rung.`,
  },
  {
    id: "recurring",
    tag: "recurring",
    eyebrow: "Recurring · the base plate",
    fragment: `A few ideas recur at every rung.`,
    sub: `Understand one layer below · everything is a tradeoff · the map is never the territory · and, from here up, reach is bought with certainty.`,
    anchor: `A step-back interlude naming ideas that reappear on every rung rather than living on one. Three that the classical half has already earned, drawn from below: (1) it pays to understand one layer below — you can use the top without the bottom, but each level you grasp deeper stops being magic; (2) everything is a tradeoff — almost nothing is simply good, so choose the sacrifice on purpose, not by accident; (3) the map is not the territory — squeezing a messy real want into symbols always drops something, so a metric is not the goal, a model is not the world, a spec is not the need, and the deepest failures live in that gap. Then add the hinge that turns the deck toward its second half — the epistemic ladder, stated plainly here for the first time: as we climb in reach, we descend in certainty. Everything below this rung was exact, inspectable, reproducible; everything above it trades some of that guarantee for the ability to handle things we could never write down. This idea is forward-pointing — it names what the learning and AI sections are about to spend — so introduce it as the bridge, not as a fully-argued claim; the rungs above pay it off. Keep it as synthesis of what recurs plus one signpost forward, not as four flat topics.`,
  },
  {
    id: "learningparadigm",
    tag: "the shift",
    eyebrow: "Learning · the paradigm",
    fragment: `Stop writing the rules — show examples instead.`,
    sub: `For messy tasks nobody can spell out, you don't program the answer; you supply examples and let the machine find the rule. The trade: the data becomes the program — more reach, fewer guarantees.`,
    anchor: `The section-opening paradigm shift, the counterpart to the root slide but for data. Everything up to here was the classical stack: a human writes explicit rules and a deterministic machine follows them. Some tasks defeat that approach — recognising a cat, flagging spam, translating a sentence — because nobody can enumerate the rules; the rule lives in millions of examples, not in a spec. Machine learning inverts the classical arrangement: instead of writing the how, you provide examples of the what (inputs and desired outputs) and an algorithm searches for a rule that fits them and, crucially, extends to new cases. Frame this squarely as the defining TRADEOFF of the paradigm, in the deck's own tradeoff idiom, so opportunity and cost arrive together rather than the section reading as a list of dangers: what you GAIN is reach — you can now handle tasks too messy, too various, or too shifting to ever specify by hand, and you get it cheaply from observation instead of exhaustive authorship; what you SPEND is guarantee and legibility — (1) the rules are now learned, not authored, so they are statistical and approximate rather than exact, the point where the deterministic stack starts giving way to the probabilistic one the AI section completes; (2) the data becomes the real program — the examples, not the code, now decide behaviour, so their gaps and biases become the system's, and "who chose the examples" becomes a first-class engineering question; (3) the machine finds correlation, not understanding, and success is judged on unseen cases, not the examples shown. The four rungs above unpack the mechanics and the costs (points in space, correlation-not-cause, generalization, calibrated trust); the gains show up when someone pulls on them (a task you could never have coded, now working). Stay at section-opener altitude: name the inversion as a genuine bargain — real reach for real guarantee — and point down the section, without descending into embeddings, evaluation, or uncertainty yet.`,
  },
  {
    id: "space",
    tag: "points in space",
    eyebrow: "Learning · representation",
    fragment: `Turn anything into points in space.`,
    sub: `Emails, faces, sentences — all become coordinates, arranged so similar things sit close. Then "find similar" is just geometry.`,
    anchor: `The move that starts machine learning working FOR you — the productive engine of the section, not a caveat: represent anything — a photo, a word, a customer — as a point in a space of numbers, engineered so that similar things land near each other and different things land far apart. Once meaning becomes distance, "find similar," "group," and "recommend" turn into geometry — this is where the reach promised at learningparadigm actually gets delivered, and it is worth letting this rung feel powerful, since the neighbouring rungs are about limits. This is representation again (foreshadowed by root's "meaning is a convention on top of bits," now learned rather than authored), aimed at learning. Keep concrete; don't explain embedding math or dimensions. Differentiate from the neighbouring rungs: this is the spatial-representation idea (the mechanism that works), not correlation and not generalization (the limits that qualify it).`,
  },
  {
    id: "correlation",
    tag: "correlation",
    eyebrow: "Learning · what patterns are",
    fragment: `Patterns are correlation, not causation.`,
    sub: `Data shows what goes together, never why — and the world drifts away from the snapshot you trained on.`,
    anchor: `Models find correlations — what tends to occur with what — not reasons or causes. Prediction is not explanation: knowing two things move together does not tell you one drives the other, or that a hidden third thing drives both. This is the "map is not the territory" idea in its learning-section form — the model captures the shadow of the world, not its mechanism. Worse, the data is a snapshot; the world keeps moving, so patterns learned yesterday quietly go stale (drift), with no warning — the same drift the defensive rung told us to expect, now arriving inside the model itself. Keep concrete. Differentiate from neighbours: this rung is correlation-not-cause plus drift; the spatial rung was the representation that works, and the next rung is generalizing to unseen cases.`,
  },
  {
    id: "generalization",
    tag: "generalizing",
    eyebrow: "Learning · the real goal",
    fragment: `Learning means guessing well on the unseen.`,
    sub: `Not memorizing the examples — generalizing to tomorrow's. We can only estimate that, and must expect some error.`,
    anchor: `Success is graded only on held-out, unseen cases: the goal is generalization, not memorizing the training examples. Because the true future can never be tested, we estimate generalization with proxies — a held-back test set — and must accept a residual error: the model will be wrong on some unseen cases, and honest practice prepares for that rather than hiding it. Note the recurring shapes here so the rung isn't just a warning: the test set is a MAP of future performance, not the territory, so it can be gamed exactly like any metric that becomes a target (Goodhart, from the algorithm rung); and "expect to be wrong and build for it" is the defensive rung's posture applied to prediction. This is the honest core of the epistemic descent — power that comes with a quantified, unavoidable error rate. Differentiate from neighbours: the previous rung was correlation and drift; this rung is the memorization trap and honest evaluation; the next is per-prediction uncertainty.`,
  },
  {
    id: "uncertainty",
    tag: "how sure?",
    eyebrow: "Learning · trust",
    fragment: `A prediction is only useful if you know how much to trust it.`,
    sub: `A guess without its confidence is half a guess — "probably rain" and "certainly rain" are different decisions.`,
    anchor: `A prediction without a calibrated sense of its own reliability is dangerous, because it invites equal trust in a near-certainty and a wild guess. Good models report how sure they are, and that confidence must be honest (calibrated): of all the times it says 70%, it should be right about seventy in a hundred. Knowing the uncertainty changes the decision — act on the confident call, verify or hedge the shaky one. This is the constructive resolution of the whole epistemic descent: certainty, once lost, can at least be MEASURED and reported, which is what makes an approximate system safe to use rather than merely unreliable. That is the bridge into the AI section: "probably rain" is the friendly face of "probably right," and honest confidence is precisely what lets the verifying step (probably) know where to look. Keep concrete. This rung quietly foreshadows the whole AI section's "probably right" theme.`,
  },
  {
    id: "nextword",
    tag: "next word",
    eyebrow: "The AI paradigm · the task",
    fragment: `Modern AI just predicts the next word.`,
    sub: `Guess the next word well enough, over enough of everything, and grammar, facts and even reasoning arrive as side effects — and whatever it read becomes part of the program.`,
    anchor: `Large language models are trained on one embarrassingly simple task: given some text, predict the next word (token), across vast corpora. The audience-facing line should stay deliberately deflationary — "it just predicts the next word" — because that honest deflation is what dissolves the magic and sets up the real surprise. But hold the balanced truth in reserve, to release as the listener pulls on it: done well enough, at enough scale, grammar, facts, style and something like reasoning emerge as side effects nobody hand-coded. This is the composition theme (steps, stacks) reaching its strangest form — the capability is really "just" composed next-word prediction, AND the composition yields functional behaviour no one explicitly built or can fully enumerate. Both halves are true; resist collapsing to either "mere autocomplete" or "mysterious mind." The twist that matters for the rest of the deck: the training data becomes part of the "codebase" — behaviour is shaped by whatever it read — so this is the learning paradigm's data-as-program tradeoff at full scale, and control over output quality becomes probabilistic and harder to guarantee than ordinary code. Keep concrete. Differentiate from the next rungs: this is the task plus emergent abilities plus data-as-codebase; scale, economics and the probabilistic-layer shift come after.`,
  },
  {
    id: "scale",
    tag: "scale",
    eyebrow: "The AI paradigm · the engine",
    fragment: `Scale is the engine — and it runs on GPUs.`,
    sub: `Billions of knobs, trillions of words of training. It works only when huge, and huge means massive parallel arithmetic — new abilities seem to appear from nowhere.`,
    anchor: `The next-word trick only produces its magic at enormous scale: models carry hundreds of billions of adjustable parameters ("knobs") tuned on trillions of tokens. That scale is enabled by hardware (GPUs, built for massive parallel arithmetic) and by software (frameworks that parallelize and optimize that arithmetic) — the AI boom is, underneath, the memory-and-arithmetic story from earlier rungs at civilizational scale. Past certain scales, new abilities appear as if from nowhere (emergence). Keep "as if from nowhere" for the room — it is the honest felt experience — but hold the hedge in the anchor and let it out as a thread: the abilities are not truly acausal, they are the map emerging from composition faster than we can author or even perceive it. We built the rule-driven, composed machinery, but the resulting behaviour is no longer something we wrote down or can fully trace — which is precisely why it can look like magic while remaining, mechanically, just composition. (Note too that some "emergence" is partly a measurement artifact — a sharp metric on a smooth underlying trend — a live instance of "the map is not the territory," best offered as a thread rather than a cold-open claim.) Keep the room-facing version concrete. Differentiate from neighbours: the previous rung was the task; this rung is why scale + GPUs, and the emergence it produces; the next is train-once economics.`,
  },
  {
    id: "trainonce",
    tag: "train once",
    eyebrow: "The AI paradigm · the economics",
    fragment: `Learn once, expensively. Use it a billion times, cheaply.`,
    sub: `One costly general model, frozen, then pointed at thousands of tasks — increasingly acting, not just answering.`,
    anchor: `The economics flip: training a large model costs a fortune, once; afterwards the model is frozen and can be used countless times for a tiny cost each. This is the os rung's "one machine shared among many" at another level — one general capability, trained on no task in particular, amortized across thousands of specific jobs. And it names the frontier the final rungs depend on: the shift from answering (produce text) to acting (call tools, take steps, carry out goals) — agents — which is set up here and made concrete at the closing rung. Keep concrete. Differentiate from neighbours: the previous rung was scale and hardware; this rung is the cost asymmetry and the turn toward acting; probably is what that does to trust, and agents is what it looks like when it acts.`,
  },
  {
    id: "probably",
    tag: "the new layer",
    eyebrow: "The AI paradigm · the shift",
    fragment: `The new layer only promises to be probably right.`,
    sub: `We're swapping exact translators between layers for statistical ones: more reach, weaker guarantee. That buys genuinely new things — and it's why you keep the verifying step.`,
    anchor: `The payoff rung, where the deck's two ladders meet. Every previous layer of the stack was a deterministic, inspectable translation — a compiler is right, or it is a compiler bug. AI turns the translation between layers (intent → code, goal → plan, question → decision) statistical: it guesses where every layer below computed. State this as a genuine BARGAIN with two real sides, not as a warning — this is the balanced counterpart to nextword's deflation. What is gained is not trivial: natural language is richer than code, so a statistical layer can attempt things no one could ever specify exactly — it reaches tasks that were simply unreachable, and that reach is real, not hype. What is spent is control and certainty: the same richness is vaguer than code (which is exactly why programming languages were invented; automation now walks that back), and the layer fails quietly and fluently — confident, well-formed, wrong. This is the epistemic ladder, named at recurring, reaching its floor: we have climbed to the top in reach and, in the same motion, descended to "probably" in certainty. What is genuinely new: for the first time the layer you trust does not promise to be right, only probably right — so the human verifying step, which deterministic layers let us safely automate away, must be kept. This very deck runs on such a layer; the lecturer on stage is the verifying step. Set up the final rung: this trade gets sharper the moment the probably-right layer stops merely answering and starts acting.`,
  },
{
    id: "agents",
    tag: "agents",
    eyebrow: "The AI paradigm · when it acts",
    fragment: `Now let it act — not just answer.`,
    sub: `Hand a probably-right system real tools and a goal, and its guesses become actions in the world. Every earlier idea meets here — and the verifying step stops being optional.`,
    anchor: `The closing rung: not a new mechanism but an INSTANTIATION that makes the whole deck concrete and urgent. An agent is a model given tools and a goal that it pursues over many steps — reading, calling, deciding, acting — instead of returning one answer. This is where the abstract "probably right" acquires teeth: a wrong answer you read and discard; a wrong ACTION executes, and across a chain of steps small probabilistic errors compound into outcomes no single step intended. Pull the deck's threads together here rather than introducing new theory — each earlier rung reappears with consequences: drift and correlation-not-cause mean the plan can be confidently based on a stale or spurious pattern; leaky abstractions mean the borrowed tool behaves in ways the model didn't foresee; the map-is-not-the-territory gap between the stated goal and the real want (a spec is not the need) is now optimized against at machine speed, Goodhart with a motor; and "understand one layer below / build defensively / keep the verifying step" stop being craftsmanship and become the load-bearing safeguards of a system that acts on probability. Frame agents as the honest reason all of this literacy matters now: the least-certain layer we have built is being handed the most capacity to act, so the verifying step — human judgment placed where the guarantee used to be — is the live problem, not a footnote. This is an opener, not a survey: agentic AI is its own large subject; the rung's job is to make the stakes vivid and point the audience toward it, closing the climb on why understanding the whole ladder is what lets you place that verifying step well. Keep concrete; resist turning it into a taxonomy of agent architectures.`,
  },
]